LANGUAGE: 'ja'
TIMEZONE_HOURS: 9
TIMEZONE_STR: 'UTC+0900'

COMMAND_PREFIX: '-'
REGION: 'asia' # ru, eu, na, asia
PLAYERS_WOWS_API_URL: "https://api.worldofwarships{region_str}/wows/account/list/"
PERSONAL_DATA_WOWS_API_URL: 'https://api.worldofwarships{region_str}/wows/account/info/'

cogs:
  - cogs.PlayerCog # cogsのディレクトリ位置を指定する

API_PLAYER_NAME_LENGTH: 24